-- One-time seed for emojis (SQLite/Turso). Do not re-run on a populated DB.
CREATE TABLE IF NOT EXISTS module_emojis (
  key   TEXT PRIMARY KEY,
  value TEXT NOT NULL
);

INSERT INTO module_emojis(key,value) VALUES('editorConfig','{"title":"Emojis","description":"Adds /emoji-add and /emoji-copy commands for uploading or cloning custom server emojis.","fields":[{"key":"emojiRoleId","label":"Emoji manager role","type":"role","store":"config","help":"Members with this role can use /emoji-add and /emoji-copy. Administrators always can. Leave empty for admins only."},{"key":"disabled","label":"Disabled reply","type":"text","help":"Shown when someone uses an emoji command while this module is turned off."},{"key":"noPermission","label":"No permission","type":"text","help":"Shown when the user lacks Administrator and the emoji manager role."},{"key":"invalidName","label":"Invalid name","type":"text","help":"Shown when the emoji name is not 2–32 alphanumeric/underscore characters."},{"key":"nameTaken","label":"Name taken","type":"text","help":"Shown when the server already has an emoji with that name."},{"key":"notImage","label":"Not an image","type":"text","help":"Shown when /emoji-add attachment is not an image file."},{"key":"fileTooLarge","label":"File too large","type":"text","help":"Shown when the image exceeds Discord''s 256 KiB emoji limit."},{"key":"notCustomEmoji","label":"Not a custom emoji","type":"text","help":"Shown when /emoji-copy is given a unicode emoji instead of a custom emoji."},{"key":"downloadFailed","label":"Download failed","type":"text","help":"Shown when the bot could not fetch the attachment or CDN image."},{"key":"botMissingPermission","label":"Bot missing permission","type":"text","help":"Shown when the bot lacks Manage Emojis and Stickers."},{"key":"slotsFull","label":"Emoji slots full","type":"text","help":"Shown when the server has no remaining emoji slots (boost tier limit)."},{"key":"createFailed","label":"Create failed","type":"text","help":"Catch-all when emoji creation fails for an unmapped reason."},{"key":"addedSuccess","label":"Success reply","type":"text","help":"Shown when an emoji is created. Token: {emoji}"}]}') ON CONFLICT(key) DO UPDATE SET value=excluded.value;
INSERT INTO module_emojis(key,value) VALUES('enabled','true') ON CONFLICT(key) DO UPDATE SET value=excluded.value;
INSERT INTO module_emojis(key,value) VALUES('emojiRoleId','""') ON CONFLICT(key) DO UPDATE SET value=excluded.value;
INSERT INTO module_emojis(key,value) VALUES('disabled','"This command is currently disabled."') ON CONFLICT(key) DO UPDATE SET value=excluded.value;
INSERT INTO module_emojis(key,value) VALUES('noPermission','"You do not have permission to manage server emojis."') ON CONFLICT(key) DO UPDATE SET value=excluded.value;
INSERT INTO module_emojis(key,value) VALUES('invalidName','"Invalid emoji name. Use 2–32 characters: letters, numbers, and underscores only."') ON CONFLICT(key) DO UPDATE SET value=excluded.value;
INSERT INTO module_emojis(key,value) VALUES('nameTaken','"An emoji with that name already exists on this server."') ON CONFLICT(key) DO UPDATE SET value=excluded.value;
INSERT INTO module_emojis(key,value) VALUES('notImage','"The attachment must be an image file (PNG, JPEG, GIF, or WebP)."') ON CONFLICT(key) DO UPDATE SET value=excluded.value;
INSERT INTO module_emojis(key,value) VALUES('fileTooLarge','"That image is too large. Discord emojis must be 256 KiB or smaller."') ON CONFLICT(key) DO UPDATE SET value=excluded.value;
INSERT INTO module_emojis(key,value) VALUES('notCustomEmoji','"Only custom emojis can be copied. Paste a custom emoji from another server (not a standard unicode emoji)."') ON CONFLICT(key) DO UPDATE SET value=excluded.value;
INSERT INTO module_emojis(key,value) VALUES('downloadFailed','"Could not download the image. Please try again."') ON CONFLICT(key) DO UPDATE SET value=excluded.value;
INSERT INTO module_emojis(key,value) VALUES('botMissingPermission','"I do not have the Manage Emojis and Stickers permission in this server."') ON CONFLICT(key) DO UPDATE SET value=excluded.value;
INSERT INTO module_emojis(key,value) VALUES('slotsFull','"This server has no remaining emoji slots. Remove an emoji or increase your boost level."') ON CONFLICT(key) DO UPDATE SET value=excluded.value;
INSERT INTO module_emojis(key,value) VALUES('createFailed','"Could not create the emoji. Please try again."') ON CONFLICT(key) DO UPDATE SET value=excluded.value;
INSERT INTO module_emojis(key,value) VALUES('addedSuccess','"Added {emoji} to this server."') ON CONFLICT(key) DO UPDATE SET value=excluded.value;
