-- One-time seed for reaction-roles (SQLite/Turso). Do not re-run on a populated DB.
CREATE TABLE IF NOT EXISTS module_reaction_roles (
  key   TEXT PRIMARY KEY,
  value TEXT NOT NULL
);

INSERT INTO module_reaction_roles(key,value) VALUES('editorConfig','{"title":"Reaction Roles","description":"Embed role panels with buttons, emoji reactions, or a dropdown. Configure each panel, save, then publish to Discord.","fields":[{"key":"disabled","label":"Module disabled message","type":"text","store":"texts"},{"key":"panelUnpublished","label":"Panel unavailable message","type":"text","store":"texts"},{"key":"invalidInteraction","label":"Invalid interaction message","type":"text","store":"texts"},{"key":"cooldown","label":"Cooldown message","type":"text","store":"texts"},{"key":"roleError","label":"Role update error message","type":"text","store":"texts"},{"key":"roleHierarchyError","label":"Role hierarchy error message","type":"text","store":"texts"},{"key":"panels","label":"Role panels","type":"object-list","store":"config","itemLabel":"Panel","publishable":true,"collapsible":true,"defaultItem":{"id":"","published":false,"channelId":"","reactionType":"button","toggleable":true,"panelTitle":"Pick your roles","panelDescription":"","ephemeralMessage":"","roleOptions":[]},"itemFields":[{"key":"channelId","label":"Channel","type":"channel","store":"config","help":"The panel message is posted here."},{"key":"reactionType","label":"Interaction type","type":"select","store":"config","options":[{"value":"button","label":"Buttons"},{"value":"emoji","label":"Emoji reactions"},{"value":"dropdown","label":"Dropdown (multi-select)"},{"value":"dropdown-single","label":"Dropdown (single-select)"}]},{"key":"toggleable","label":"Allow toggling roles","type":"boolean","store":"config","help":"When enabled, pressing again removes the role. When disabled, roles are assigned once."},{"key":"panelTitle","label":"Embed title","type":"text","store":"texts"},{"key":"panelDescription","label":"Embed description","type":"textarea","store":"texts"},{"key":"ephemeralMessage","label":"Ephemeral reply (optional)","type":"textarea","store":"texts","visibleWhen":{"reactionType":["button","dropdown","dropdown-single"]},"clearWhenHidden":true,"help":"Button and dropdown only. Sent privately after a successful interaction when filled in. Tokens: {mention}, {role}. Leave blank for no reply."},{"key":"roleOptions","label":"Role options","type":"option-list","store":"config","optionFields":[{"key":"roleId","label":"Role","type":"role","store":"config"},{"key":"emoji","label":"Emoji","type":"text","store":"config","help":"Required for emoji reaction mode — each option must use a different emoji (do not reuse the same one twice). Optional decoration for buttons and dropdowns."},{"key":"label","label":"Label","type":"text","store":"config","help":"Button or dropdown option label. Required for button and dropdown modes."}]}]}]}') ON CONFLICT(key) DO UPDATE SET value=excluded.value;
INSERT INTO module_reaction_roles(key,value) VALUES('enabled','true') ON CONFLICT(key) DO UPDATE SET value=excluded.value;
INSERT INTO module_reaction_roles(key,value) VALUES('panels','[]') ON CONFLICT(key) DO UPDATE SET value=excluded.value;
INSERT INTO module_reaction_roles(key,value) VALUES('disabled','"Reaction roles are currently disabled."') ON CONFLICT(key) DO UPDATE SET value=excluded.value;
INSERT INTO module_reaction_roles(key,value) VALUES('panelUnpublished','"This role panel is not available right now."') ON CONFLICT(key) DO UPDATE SET value=excluded.value;
INSERT INTO module_reaction_roles(key,value) VALUES('invalidInteraction','"This interaction does not match a valid role panel."') ON CONFLICT(key) DO UPDATE SET value=excluded.value;
INSERT INTO module_reaction_roles(key,value) VALUES('cooldown','"Please wait a moment before trying again."') ON CONFLICT(key) DO UPDATE SET value=excluded.value;
INSERT INTO module_reaction_roles(key,value) VALUES('roleError','"Could not update your roles. Please contact an administrator."') ON CONFLICT(key) DO UPDATE SET value=excluded.value;
INSERT INTO module_reaction_roles(key,value) VALUES('roleHierarchyError','"The bot cannot assign one or more of these roles."') ON CONFLICT(key) DO UPDATE SET value=excluded.value;
