-- One-time seed for pic-repost-commands (SQLite/Turso). Do not re-run on a populated DB.
CREATE TABLE IF NOT EXISTS module_pic_repost_commands (
  key   TEXT PRIMARY KEY,
  value TEXT NOT NULL
);

INSERT INTO module_pic_repost_commands(key,value) VALUES('editorConfig','{"title":"Pic Repost Commands","description":"Adds /pic and /post commands that re-upload attached images with attribution and a comments thread.","fields":[{"key":"deleteEmoji","label":"Delete reaction emoji","type":"text","store":"config","help":"Emoji the post author can react with to delete their repost. Unicode (🗑️) or custom (<:name:id>)."},{"key":"deleteAuthorLastMention","label":"Last mention is delete author","type":"boolean","store":"config","help":"When on (default), delete-by-reaction uses the last user mention in the caption — put {mention} after {message} so mentions inside the caption text are not treated as the author. When off, the first mention is used instead."},{"key":"disabled","label":"Disabled reply","type":"text","help":"Shown when someone uses /pic or /post while this module is turned off."},{"key":"noImages","label":"No images attached","type":"text","help":"Shown when the user runs the command without attaching an image."},{"key":"notImages","label":"Non-image attachments","type":"text","help":"Shown when attachments are not images. Tokens: {names}"},{"key":"attachmentTooLarge","label":"Attachment too large","type":"textarea","help":"Shown when an image exceeds this server''s upload limit (set by boost level). Tokens: {names}, {limit}"},{"key":"messageTooLong","label":"Message too long","type":"text","help":"Shown when the caption exceeds Discord''s 2000 character limit."},{"key":"downloadFailed","label":"Download failed","type":"text","help":"Shown when an attached image could not be downloaded."},{"key":"cannotPost","label":"Cannot post","type":"text","help":"Shown when the bot cannot post in the channel."},{"key":"postFailed","label":"Post failed","type":"textarea","help":"Shown when posting the images to the channel fails (size/permission issues)."},{"key":"attribution","label":"Attribution caption","type":"textarea","help":"Caption posted with the re-uploaded images. Tokens: {message}, {mention}, {deleteEmoji}. Place {mention} after {message} so delete-by-reaction identifies the post author correctly."},{"key":"postedSuccess","label":"Success reply","type":"text","help":"Confirmation shown to the author. Tokens: {count}, {images}"},{"key":"threadNote","label":"Thread failure note","type":"textarea","help":"Appended to the success reply when the comments thread could not be created."},{"key":"threadFirstMessage","label":"Thread opener","type":"textarea","help":"First message posted in the comments thread."}]}') ON CONFLICT(key) DO UPDATE SET value=excluded.value;
INSERT INTO module_pic_repost_commands(key,value) VALUES('enabled','true') ON CONFLICT(key) DO UPDATE SET value=excluded.value;
INSERT INTO module_pic_repost_commands(key,value) VALUES('deleteEmoji','"🗑️"') ON CONFLICT(key) DO UPDATE SET value=excluded.value;
INSERT INTO module_pic_repost_commands(key,value) VALUES('deleteAuthorLastMention','true') ON CONFLICT(key) DO UPDATE SET value=excluded.value;
INSERT INTO module_pic_repost_commands(key,value) VALUES('disabled','"This command is currently disabled."') ON CONFLICT(key) DO UPDATE SET value=excluded.value;
INSERT INTO module_pic_repost_commands(key,value) VALUES('noImages','"You need to attach at least one image."') ON CONFLICT(key) DO UPDATE SET value=excluded.value;
INSERT INTO module_pic_repost_commands(key,value) VALUES('notImages','"These attachments are not images: {names}. Please attach image files only."') ON CONFLICT(key) DO UPDATE SET value=excluded.value;
INSERT INTO module_pic_repost_commands(key,value) VALUES('messageTooLong','"Your message is too long. Please keep it under 2000 characters."') ON CONFLICT(key) DO UPDATE SET value=excluded.value;
INSERT INTO module_pic_repost_commands(key,value) VALUES('attachmentTooLarge','"One or more images are too large: {names}. This server allows up to {limit} per file."') ON CONFLICT(key) DO UPDATE SET value=excluded.value;
INSERT INTO module_pic_repost_commands(key,value) VALUES('downloadFailed','"Could not download one of your images. Please try again with a smaller or different file."') ON CONFLICT(key) DO UPDATE SET value=excluded.value;
INSERT INTO module_pic_repost_commands(key,value) VALUES('cannotPost','"I cannot post in this channel."') ON CONFLICT(key) DO UPDATE SET value=excluded.value;
INSERT INTO module_pic_repost_commands(key,value) VALUES('postFailed','"I could not post in this channel. This is usually a file size limit or missing \"Send Messages\"/\"Attach Files\" permission."') ON CONFLICT(key) DO UPDATE SET value=excluded.value;
INSERT INTO module_pic_repost_commands(key,value) VALUES('attribution','"{message}\n\nby {mention}\n\nReact with {deleteEmoji} to delete"') ON CONFLICT(key) DO UPDATE SET value=excluded.value;
INSERT INTO module_pic_repost_commands(key,value) VALUES('postedSuccess','"Posted {count} {images} to this channel."') ON CONFLICT(key) DO UPDATE SET value=excluded.value;
INSERT INTO module_pic_repost_commands(key,value) VALUES('threadNote','"\n\nNote: I could not create the comments thread. I may be missing the \"Create Public Threads\" / \"Send Messages in Threads\" permission in this channel."') ON CONFLICT(key) DO UPDATE SET value=excluded.value;
INSERT INTO module_pic_repost_commands(key,value) VALUES('threadFirstMessage','"Please comment here in the thread to not clutter the channel.\n\nBitte hier im Thread kommentieren um nicht den Channel zu überlasten."') ON CONFLICT(key) DO UPDATE SET value=excluded.value;
