-- One-time seed for moderation-log (SQLite/Turso). Do not re-run on a populated DB.
CREATE TABLE IF NOT EXISTS module_moderation_log (
  key        TEXT PRIMARY KEY,
  value      TEXT NOT NULL,
  updated_at INTEGER NOT NULL DEFAULT 0
);

INSERT INTO module_moderation_log(key,value,updated_at) VALUES('editorConfig','{"title":"Moderation Log","description":"Posts embed logs to a channel when messages are deleted or members leave, are kicked, banned, or unbanned.","fields":[{"key":"channelId","label":"Log channel","type":"channel","store":"config","help":"Channel where moderation events are posted. Leave empty to disable."},{"key":"logMessageDeleted","label":"Log deleted messages","type":"boolean","store":"config"},{"key":"logMemberLeft","label":"Log member leave","type":"boolean","store":"config"},{"key":"logMemberKicked","label":"Log member kick","type":"boolean","store":"config"},{"key":"logMemberBanned","label":"Log member ban","type":"boolean","store":"config"},{"key":"logMemberUnbanned","label":"Log member unban","type":"boolean","store":"config"},{"key":"messageDeleted","label":"Deleted message line","type":"text","help":"Tokens: {author}, {channel}"},{"key":"messageDeletedEmpty","label":"Deleted message (no text)","type":"text","help":"Shown when the deleted message had no text content."},{"key":"authorUnknown","label":"Unknown author","type":"text","help":"Used for {author} and the embed author name when Discord sends no author (e.g. bulk/system deletes)."},{"key":"memberLeft","label":"Member left","type":"text","help":"Tokens: {mention}"},{"key":"memberKicked","label":"Member kicked","type":"text","help":"Tokens: {mention}, {executorId}"},{"key":"memberBanned","label":"Member banned","type":"text","help":"Tokens: {mention}, {executorId}"},{"key":"memberUnbanned","label":"Member unbanned","type":"text","help":"Tokens: {mention}, {executorId}"},{"key":"executorUnknown","label":"Unknown moderator","type":"text","help":"Substituted for {executorId} when the audit log has no executor."},{"key":"footerMessageId","label":"Footer (deleted message)","type":"text","help":"Tokens: {messageId}"},{"key":"footerUserId","label":"Footer (member events)","type":"text","help":"Tokens: {userId}"}]}',0) ON CONFLICT(key) DO UPDATE SET value=excluded.value, updated_at=excluded.updated_at;
INSERT INTO module_moderation_log(key,value,updated_at) VALUES('channelId','""',0) ON CONFLICT(key) DO UPDATE SET value=excluded.value, updated_at=excluded.updated_at;
INSERT INTO module_moderation_log(key,value,updated_at) VALUES('logMessageDeleted','true',0) ON CONFLICT(key) DO UPDATE SET value=excluded.value, updated_at=excluded.updated_at;
INSERT INTO module_moderation_log(key,value,updated_at) VALUES('logMemberLeft','true',0) ON CONFLICT(key) DO UPDATE SET value=excluded.value, updated_at=excluded.updated_at;
INSERT INTO module_moderation_log(key,value,updated_at) VALUES('logMemberKicked','true',0) ON CONFLICT(key) DO UPDATE SET value=excluded.value, updated_at=excluded.updated_at;
INSERT INTO module_moderation_log(key,value,updated_at) VALUES('logMemberBanned','true',0) ON CONFLICT(key) DO UPDATE SET value=excluded.value, updated_at=excluded.updated_at;
INSERT INTO module_moderation_log(key,value,updated_at) VALUES('logMemberUnbanned','true',0) ON CONFLICT(key) DO UPDATE SET value=excluded.value, updated_at=excluded.updated_at;
INSERT INTO module_moderation_log(key,value,updated_at) VALUES('messageDeleted','"🗑️ Message sent by {author} deleted in {channel}"',0) ON CONFLICT(key) DO UPDATE SET value=excluded.value, updated_at=excluded.updated_at;
INSERT INTO module_moderation_log(key,value,updated_at) VALUES('messageDeletedEmpty','"[no text content]"',0) ON CONFLICT(key) DO UPDATE SET value=excluded.value, updated_at=excluded.updated_at;
INSERT INTO module_moderation_log(key,value,updated_at) VALUES('authorUnknown','"Unknown user"',0) ON CONFLICT(key) DO UPDATE SET value=excluded.value, updated_at=excluded.updated_at;
INSERT INTO module_moderation_log(key,value,updated_at) VALUES('memberLeft','"📤 {mention} has left the server"',0) ON CONFLICT(key) DO UPDATE SET value=excluded.value, updated_at=excluded.updated_at;
INSERT INTO module_moderation_log(key,value,updated_at) VALUES('memberKicked','"👮 {mention} has been kicked by {executorId}"',0) ON CONFLICT(key) DO UPDATE SET value=excluded.value, updated_at=excluded.updated_at;
INSERT INTO module_moderation_log(key,value,updated_at) VALUES('memberBanned','"👮 🔒 {mention} has been banned by {executorId}"',0) ON CONFLICT(key) DO UPDATE SET value=excluded.value, updated_at=excluded.updated_at;
INSERT INTO module_moderation_log(key,value,updated_at) VALUES('memberUnbanned','"🔓 {mention} has been unbanned by {executorId}"',0) ON CONFLICT(key) DO UPDATE SET value=excluded.value, updated_at=excluded.updated_at;
INSERT INTO module_moderation_log(key,value,updated_at) VALUES('executorUnknown','"Unknown"',0) ON CONFLICT(key) DO UPDATE SET value=excluded.value, updated_at=excluded.updated_at;
INSERT INTO module_moderation_log(key,value,updated_at) VALUES('footerMessageId','"Message ID: {messageId}"',0) ON CONFLICT(key) DO UPDATE SET value=excluded.value, updated_at=excluded.updated_at;
INSERT INTO module_moderation_log(key,value,updated_at) VALUES('footerUserId','"ID: {userId}"',0) ON CONFLICT(key) DO UPDATE SET value=excluded.value, updated_at=excluded.updated_at;
