-- One-time seed for links-pics-vids-autothread (SQLite/Turso). Do not re-run on a populated DB.
CREATE TABLE IF NOT EXISTS module_links_pics_vids_autothread (
  key   TEXT PRIMARY KEY,
  value TEXT NOT NULL
);

INSERT INTO module_links_pics_vids_autothread(key,value) VALUES('editorConfig','{"title":"Auto-Thread","description":"Auto-creates a comments thread on posts with images, videos, supported social posts, or direct Discord media links in watched channels.","fields":[{"key":"channelIds","label":"Watched channels","type":"channel-multi","store":"config","help":"Channels where the bot auto-creates a comments thread on qualifying posts."},{"key":"deleteNonQualifyingMessages","label":"Delete non-qualifying posts","type":"boolean","store":"config","help":"When on, messages without images, videos, or supported post links are deleted and the author receives a DM asking them to use comments threads."},{"key":"threadFirstMessage","label":"Thread opener","type":"textarea","help":"First message posted in the auto-created comments thread."},{"key":"nonQualifyingDm","label":"Non-qualifying post DM","type":"textarea","help":"Sent privately when a non-qualifying post is deleted. Tokens: {channel} (clickable channel link), {message}. Text over 2000 characters is sent as an embed automatically."}]}') ON CONFLICT(key) DO UPDATE SET value=excluded.value;
INSERT INTO module_links_pics_vids_autothread(key,value) VALUES('enabled','true') ON CONFLICT(key) DO UPDATE SET value=excluded.value;
INSERT INTO module_links_pics_vids_autothread(key,value) VALUES('channelIds','[]') ON CONFLICT(key) DO UPDATE SET value=excluded.value;
INSERT INTO module_links_pics_vids_autothread(key,value) VALUES('deleteNonQualifyingMessages','false') ON CONFLICT(key) DO UPDATE SET value=excluded.value;
INSERT INTO module_links_pics_vids_autothread(key,value) VALUES('threadFirstMessage','"Please comment here in the thread to not clutter the channel.\n\nBitte hier im Thread kommentieren um nicht den Channel zu überlasten."') ON CONFLICT(key) DO UPDATE SET value=excluded.value;
INSERT INTO module_links_pics_vids_autothread(key,value) VALUES('nonQualifyingDm','"Hi! Your message in {channel} was removed because this channel is for images, videos, and supported post links only. Please comment in the thread under an existing post instead of posting in the channel.\n\nHallo! Deine Nachricht in {channel} wurde entfernt, weil dieser Channel nur für Bilder, Videos und unterstützte Post-Links gedacht ist. Bitte kommentiere im Thread unter einem bestehenden Post, statt im Channel zu schreiben."') ON CONFLICT(key) DO UPDATE SET value=excluded.value;
